#!/usr/bin/env bash
"$SNAP/opt/Revolt/revolt-desktop" --no-sandbox --disable-seccomp-filter-sandbox \
	--enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer \
	--ozone-platform-hint=auto
