name: revolt-desktop # you probably want to 'snapcraft register <name>'
version: "1.0.6" # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: metadata-from-file
base: core22
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo

architectures:
  - build-on: amd64

parts:
  metadata-from-file:
    plugin: dump
    source-type: local
    source: snap/local
    organize:
      chat.revolt.revoltDesktop.appdata.xml: /usr/local/share/appdata/
    parse-info: [/usr/local/share/appdata/chat.revolt.revoltDesktop.appdata.xml]
  
  revolt:
    plugin: nil
    override-build: |
      craftctl default
      # Install corepack
      npm i -g corepack
      # Enable Corepack to install yarn
      corepack enable
      git clone https://github.com/revoltchat/desktop.git
      cd desktop
      corepack yarn
      corepack yarn build:bundle
      corepack yarn build:linux deb
      dpkg -x dist/revolt-desktop_$SNAPCRAFT_PROJECT_VERSION_amd64.deb $CRAFT_PART_INSTALL
      rm $CRAFT_PART_INSTALL/opt/Revolt/chrome-sandbox
      sed -i 's|Icon=revolt-desktop|Icon=/usr/share/icons/hicolor/512x512/apps/revolt-desktop\.png|' ${CRAFT_PART_INSTALL}/usr/share/applications/revolt-desktop.desktop
      mv ${CRAFT_PART_INSTALL}/usr/share/applications/revolt-desktop.desktop ${CRAFT_PART_INSTALL}/usr/share/applications/chat.revolt.revoltDesktop.desktop
    build-snaps: [node/18/stable]
    build-packages:
      - git
      - sed
    stage-packages:
      - libatomic1
      - libc++1
      - libnspr4
      - libnss3
      - libxss1
      - xdg-utils
    prime:
      - -usr/bin/xdg-open
  cleanup:
    after: [revolt]
    plugin: nil
    build-snaps: [gnome-42-2204]
    override-prime: |
      set -eux
      cd /snap/gnome-42-2204/current
      find . -type f,l -exec rm -f $CRAFT_PRIME/{} \;

plugs:
  shmem:
    interface: shared-memory
    private: true

apps:
  revolt:
    extensions: [gnome]
    command: opt/Revolt/revolt-desktop --no-sandbox --disable-seccomp-filter-sandbox
    common-id: chat.revolt.revoltDesktop
    autostart: revolt-desktop.desktop
    desktop: usr/share/applications/revolt-desktop.desktop
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to
      # ensure libappindicator has readable resources
      TMPDIR: $XDG_RUNTIME_DIR
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
      GTK_USE_PORTAL: 1
    plugs:
      - audio-playback
      - audio-record
      - camera
      - home
      - mount-observe
      - network
      - network-observe
      - opengl
      - process-control
      - removable-media
      - screen-inhibit-control
      - shmem
      - system-observe
      - unity7
