name: revolt-desktop # you probably want to 'snapcraft register <name>'
version: "1.0.6" # just for humans, typically '1.2+git' or '1.3.2'
summary: Find your community, connect with the world.
description: |
  Find your community, connect with the world.
  Revolt is one of the best ways to stay connected with your friends and community without sacrificing any usability.
  We focus on the user, and you can be sure that your conversations are confidential and your data is secure.

  Unofficial wrapper made by @amycatgirl#9237
base: core22
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo

architectures:
  - build-on: amd64

parts:
  custom-wrapper:
    plugin: dump
    source: snap/local/
    organize:
      launch-wrapper: bin/
  revolt:
    plugin: nil
    override-build: |
      craftctl default
      # Install corepack
      npm i -g corepack
      # Enable Corepack to install yarn
      corepack enable
      git clone https://github.com/revoltchat/desktop.git
      cd desktop
      cat package.json | jq '.version = "1.0.6+snap"' | tee package.json
      cat package.json | jq '.devDependencies.electron = "^28.2.0"' | tee package.json
      corepack yarn
      corepack yarn build:bundle
      corepack yarn build:linux deb
      dpkg -x dist/revolt-desktop_$SNAPCRAFT_PROJECT_VERSION_amd64.deb $CRAFT_PART_INSTALL
      rm $CRAFT_PART_INSTALL/opt/Revolt/chrome-sandbox
      sed -i 's|Icon=revolt-desktop|Icon=/usr/share/icons/hicolor/512x512/apps/revolt-desktop\.png|' ${CRAFT_PART_INSTALL}/usr/share/applications/revolt-desktop.desktop
      mv ${CRAFT_PART_INSTALL}/usr/share/applications/revolt-desktop.desktop ${CRAFT_PART_INSTALL}/usr/share/applications/chat.revolt.revoltDesktop.desktop
    build-snaps: [node/18/stable]
    build-packages:
      - git
      - sed
    stage-packages:
      - libatomic1
      - libc++1
      - libnspr4
      - libnss3
      - libxss1
      - xdg-utils
    prime:
      - -usr/bin/xdg-open
  cleanup:
    after: [revolt]
    plugin: nil
    build-snaps: [gnome-42-2204]
    override-prime: |
      set -eux
      cd /snap/gnome-42-2204/current
      find . -type f,l -exec rm -f $CRAFT_PRIME/{} \;

plugs:
  shmem:
    interface: shared-memory
    private: true

apps:
  revolt:
    extensions: [gnome]
    command: bin/launch-wrapper
    autostart: chat.revolt.revoltDesktop.desktop
    desktop: usr/share/applications/chat.revolt.revoltDesktop.desktop
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to
      # ensure libappindicator has readable resources
      TMPDIR: $XDG_RUNTIME_DIR
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 0
      GTK_USE_PORTAL: 1
    plugs:
      - audio-playback
      - audio-record
      - camera
      - home
      - mount-observe
      - network
      - network-observe
      - opengl
      - process-control
      - removable-media
      - screen-inhibit-control
      - shmem
      - system-observe
      - unity7
      - wayland
      - x11
      - browser-support
