name: 📦 Publish to Snapcraft

on:
  release:
    types: released

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: snapcore/action-build@v1
        id: build

      - uses: snapcore/action-publish@v1
        id: publish
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: beta
